title: 蒙古文古籍联合目录
email: hfl@huangfeilong.com
description: >- 
  涵盖所有蒙古文古籍的联合目录
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ucamb
github_username:  ucamb

# Build settings
theme: minima
minima:
  skin: dark
  date_format: "%Y年%-m月%-d日"
plugins:
  - jekyll-feed
